name: bosko
favicon: null
layout_spectrum: 0.8394020986743271
typography_spectrum: 0.6316071164328605
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5897714572492987
  lightness: 0.9968276685103774
  saturation: 0.1690703839994967
  rhythmicContrast: 0.6462300466373563
purpose: []
